# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
