# Generated by Django 6.0.2 on 2026-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
